version = 1

test_patterns = [
  "**/tests/**",
  "**/test_*.py"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  max_line_length = 120
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"
