version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
  type_checker = "mypy"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
