version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodb/data

volumes:
  dynamodb-data: {}
