
[tool.coverage.run]
source = ["."]
omit = [
    "tests/*",
    "db_helper.py",
]
relative_files = true

[tool.black]
line_length = 120

[tool.pylint]
max-line-length = 120

[tool.mypy]
exclude = "tests/*"
